apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "logger-service"
  namespace: "microservices"
  labels:
    app: "logger-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "logger-service"
  template:
    metadata:
      labels:
        app: "logger-service"
    spec:
      containers:
      - name: "logger-service-1"
        image: "us.gcr.io/learn-cloud-0809/logger_service:latest"
        env:
        - name: "SERVICE_NAME"
          valueFrom:
            configMapKeyRef:
              key: "SERVICE_NAME"
              name: "logger-service-config"
        - name: "RABBIT_MQ_URL"
          valueFrom:
            configMapKeyRef:
              key: "RABBIT_MQ_URL"
              name: "logger-service-config"
        - name: "EXCHANGE_NAME"
          valueFrom:
            configMapKeyRef:
              key: "EXCHANGE_NAME"
              name: "logger-service-config"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "logger-service-hpa-plwz"
  namespace: "microservices"
  labels:
    app: "logger-service"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "logger-service"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
