apiVersion: "v1"
kind: "Service"
metadata:
  name: "rest-service"
  namespace: "microservices"
  labels:
    app: "rest-service"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "rest-service"
  type: "LoadBalancer"
