apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "rest-service-ingress"
  namespace: "microservices"
spec:
  defaultBackend:
    service:
      name: "rest-service"
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: "/"
        backend:
          service:
            name: "rest-service"
            port:
              number: 80
        pathType: "ImplementationSpecific"
    host: "task.mirobidjon.uz"
status:
  loadBalancer: {}
