apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "rabbitmq-config"
  namespace: "microservices"
  labels:
    app: "rabbitmq"
data:
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
