apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "rest-service-config"
  namespace: "microservices"
  labels:
    app: "rest-service"
data:
  SERVICE_NAME: "rest-service"
  HTTP_PORT: ":80"
  ENVIRONMENT: "release"
  POSTGRES_HOST: *
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "rest-service"
  POSTGRES_PASSWORD: *
  POSTGRES_DATABASE: "rest-service"
  POSTGRES_MAX_CONNECTIONS: "100"
